export const KeyValue = {
    giangDuong: "Giảng đường đáp ứng yêu cầu của môn học",
    trangThietBi: "Các trang thiết bị của giảng đường đáp ứng yêu cầu giảng dạy và học tập",
    hoTroKipThoi: "Bạn được hỗ trợ kịp thời trong quá trình học môn này",
    mucTieuMonHoc: "Mục tiêu của môn học nêu rõ kiến thức và kỹ năng người học cần đạt được",
    thoiLuongMonHoc: "Thời lượng môn học được phân bổ hợp lí cho các hình thức học tập",
    taiLieu: "Các tài liệu phục vụ môn học được cập nhật",
    trangBiKienThuc: "Môn học góp phần trang bị kiến thức kĩ năng nghề nghiệp cho bạn",
    giangVienThucHienDayDu: "Giảng viên thực hiện đầy đủ nội dung và thời lượng của môn học theo kế hoạch",
    giangVienHuongDanBatDauMonHoc: "Giảng viên hướng dẫn bạn phương pháp học tập khi bắt đầu môn học",
    phuongPhapGiangDay: "Phương pháp giảng dạy của giảng viên giúp bạn phát triển tư duy",
    giangVienTaoCoHoi: "Giảng viên tạo cơ hội để bạn chủ động tham gia vào quá trình học tập",
    giangVienGiupDocLap: "Giảng viên giúp bạn phát triển kĩ năng làm việc độc lập",
    giangVienThucTien: "Giảng viên rèn luyện cho bạn phương pháp liên hệ giữa các vấn đề trong môn học với thực tiễn",
    giangVienSuDungCongCu: "Giảng viên sử dụng hiệu quả phương tiện dạy học",
    giangVienGiaoDucTuCachNguoiHoc: "Giảng viên quan tâm giáo dục tư cách, phẩm chất nghề nghiệp của người học",
    hieuBai: "Bạn hiểu những vấn đề được truyền tải trên lớp",
    cachDanhGia: "Kết quả học tập của người học được đánh giá bằng nhiều hình thức phù hợp với tính chất và đặc thù môn học",
    noiDungDanhGia: "Nội dung kiểm tra đánh giá tổng hợp được các kĩ năng mà người học phải đạt theo yêu cầu",
    tacDungThongTinPhanHoi: "Thông tin phản hồi từ kiểm tra đánh giá giúp bạn cải thiện kết quả học tập",
};